name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check formatting (black)
        run: black --check goban tests

      - name: Lint with flake8
        run: flake8 goban tests

      - name: Check imports order (isort)
        run: isort --check-only goban tests

      - name: Check typing with mypy
        run: mypy goban

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Upload coverage to GitHub summary
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

